### ISSUE TITLE
AttributeError AttributeError

### ISSUE THREAD

**Issue by materka1996** [xIceArcher/pyass#11]
Hi In my code:

import pyass

from datetime import timedelta

with open("track3.eng.ass", encoding="utf_8_sig") as f:
    script = pyass.load(f)

for event in script.events:
    if event.type == 'Dialogue':
        print(f'Text: {event.text}')

Error: 
 raise AttributeError
AttributeError

**Comment by xIceArcher** [comment]
The field is `Event.format`, not `type`
