### ISSUE TITLE
Incorrect Color Tag parsing of \c

### ISSUE THREAD

**Issue by ahuei123456** [xIceArcher/pyass#12]
When a Color Tag with prefix `\c` is passed into `Tag.parse()`, it turns into a `\1c` tag instead.

## How to reproduce

```py
import pyass

text = r"\c&H000000&"
tag = pyass.Tag.parse(r"\c&H000000&")
test = str(tag)
print(f"Original Tag: {text}\nPost-parse Tag: {test}")
```

### Output:
```
Original Tag: \c&H000000&   
Post-parse Tag: \1c&H000000&
```

I'm aware that `\1c` and `\c` are the same tag internally, so maybe this is a non-issue.

**Comment by xIceArcher** [comment]
Fixed in v0.1.4, please update to the latest version
