### ISSUE TITLE
can you add some docs or add a example

### ISSUE THREAD

**Issue by shaowei1** [xIceArcher/pyass#5]
I want to edit the Default style of an existing subtitle file subtitle.ass.

like
`
from pyass import Script, StylesSection, Style, Color

script = Script.parse("subtitle.ass")

target_style = script.styles[0]

target_style.fontName = "Arial"
target_style.fontSize = 30
target_style.primaryColor = Color.parse("#ffffff")
target_style.outlineColor = Color.parse("#000000")
script.save()
`

**Comment by xIceArcher** [comment]
A quickstart guide has been added to README.md.

**Comment by shaowei1** [comment]
I don't know why there is an extra fontSize 48 style

# subtitles.ass
`
[Script Info]
; Script generated by FFmpeg/Lavc60.3.100
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,16,&Hffffff,&H000000,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1


[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.02,0:00:00.67,Default,,0,0,0,,大家好

# example
`
with open("subtitles.ass", encoding="utf_8_sig") as f:
    script = pyass.load(f)

for style in script.styles:
    print(f'Style name: {style.name}, Font name: {style.fontName}, Font size: {style.fontSize}, Primary color: {style.primaryColor}')

#output
`
Style name: Default, Font name: Arial, Font size: 16, Primary color: &H00FFFFFF

Style name: Default, Font name: Arial, Font size: 48, Primary color: &H00FFFFFF
`

**Comment by xIceArcher** [comment]
When I run the code in your example, only one style is printed, and I am unable to replicate your issue.

Please check that you are not appending anything else to the `styles` list in your code.

**Comment by shaowei1** [comment]
Sorry, it was my fault. I accidentally added an extra blank line between Styles and Events, resulting in an extra Style.

now is ok
thank you
